### ISSUE TITLE
Make HttpJsonMetricHandler a generic HttpMetricHandler ?

### ISSUE THREAD

**Issue by tbolon** [StackExchange/StackExchange.Metrics#40]
Hi,

I am currently investigating if I could add a custom handler to write metrics to influxdb using the [line protocol](https://v2.docs.influxdata.com/v2.0/reference/syntax/line-protocol/) which consists of sending HTTP text data with 1 line per metric.

I was reading the code, and found HttpJsonMetricHandler which already handle sending data using HttpClient but specific to json. But the only code I found specific to json seems to be the content-type header, which is hardcoded.

Perhaps this class could be renamed to handle more generic http messages ?

I am certainly short-sighted and the ReadOnlySequenceContent type will certainly need more customization endpoint, for example to add custom auth headers... So in the end, I will still need to do a copy of the class.

**Comment by tbolon** [comment]
The HttpJsonMetricHandler seems to have a lot of custom methods to write rows depending on the PayloadType... I am not sure there are a lot of code which can be reused in my implementation. I had to copy the MemoryExtensions class to allow `WriteAsync(ReadOnlyMemory<byte>)` to work on netstandard.

Not sure if it's really useful in the end...

**Comment by NickCraver** [comment]
If you can hang on about a day here, we're _completely_ refactoring how this thing works. @deanward81 and I had a lot of discussions around the API and in short: we're going to decouple it. Metrics will yield a MetricReading, it'll be up to the collector to do the serialization given the metrics. Right now it's very intertwined due to the original design constraints and a lack of a dual-target path forward. Stepping back, we're re-engineering this thing and that work is kicking off this week.

**Comment by tbolon** [comment]
Got it 👍

I hope the multiple handler paradigm is here to stay. I understood that you went from bosun to SignalFx and supposed that before that you only supported one handler. I have tried a lot of Metrics libraries and did not found any focused enough (from my point of view) on memory cost. This one seems to be focused on both simplicity and performance, and it's a sweet spot for me.

**Comment by tbolon** [comment]
Disgression: and I just found [another project](https://opentelemetry.io/about/) aiming at providing an abstraction on logs/metrics... And it seems the [.net team](https://medium.com/opentelemetry/opentelemetry-net-sdk-progress-3a63dcdc6cb0) want to implement some concepts directly into the runtime to ease compatibility...

**Comment by deanward81** [comment]
I've made some changes in 00fc9cbb76db3e9f2a90225b99a3e87f3f59edde to make it slightly easier to customize the way we handle HTTP. [MyCustomHandler](https://github.com/StackExchange/StackExchange.Metrics/blob/master/samples/StackExchange.Metrics.SampleHost/MyCustomHandler.cs) in the sample project is a bare-bones way of writing metrics to plain text that will be flushed to an HTTP endpoint.

For examples of memory-efficient serialization I'd recommend taking a look at [StatsdMetricHandler](https://github.com/StackExchange/StackExchange.Metrics/blob/master/src/StackExchange.Metrics/Handlers/StatsdMetricHandler.cs)!

Let us know how it goes, I'm about to cut a 2.0 release, but hoping you have enough to work with - if not just shout!

**Comment by deanward81** [comment]
Closing this out, ping if there's anything more to be done here!
